import type { TeamMember, ServiceOrder, DashboardStats, Alert, IncidentCluster } from '@/types'

export const MOCK_TEAMS: Record<string, TeamMember> = {
  'tech-1': {
    id: 'tech-1',
    name: 'Equipe Alpha (Carlos & Marcos)',
    techs: ['Carlos Eduardo', 'Marcos Silva'],
    status: 'Em deslocamento',
    battery: 88,
    vehicle: 'Fiat Uno Ladder',
    plate: 'PSL-4091',
    phone: '(98) 98812-4091',
    region: 'Centro / Renascença',
    city: 'São Luís',
    neighborhood: 'Renascença',
    currentOSId: 'os-101',
    activityTimeMinutes: 18,
    lastSeen: 'Agora',
    lastLocation: { lat: -2.505, lng: -44.298, speed: 38, heading: 45 },
  },
  'tech-2': {
    id: 'tech-2',
    name: 'Equipe Bravo (Lucas)',
    techs: ['Lucas Ferreira'],
    status: 'Executando atendimento',
    battery: 64,
    vehicle: 'Honda Bros 160',
    plate: 'PXY-8821',
    phone: '(98) 98744-1102',
    region: 'Cohama / Vinhais',
    city: 'São Luís',
    neighborhood: 'Cohama',
    currentOSId: 'os-102',
    activityTimeMinutes: 34,
    lastSeen: 'Há 1 min',
    lastLocation: { lat: -2.528, lng: -44.256, speed: 0, heading: 0 },
  },
  'tech-3': {
    id: 'tech-3',
    name: 'Equipe Charlie (Felipe & Andre)',
    techs: ['Felipe Costa', 'André Ramos'],
    status: 'Disponível',
    battery: 95,
    vehicle: 'Strada Fusion',
    plate: 'ROA-9912',
    phone: '(98) 98112-9900',
    region: 'Calhau / Ponta d\'Areia',
    city: 'São Luís',
    neighborhood: 'Calhau',
    activityTimeMinutes: 5,
    lastSeen: 'Agora',
    lastLocation: { lat: -2.492, lng: -44.285, speed: 0, heading: 120 },
  },
  'tech-4': {
    id: 'tech-4',
    name: 'Equipe Delta (Infra Fusão)',
    techs: ['Roberto Almeida', 'Thiago Mota'],
    status: 'Executando atendimento',
    battery: 42,
    vehicle: 'Master Furgão OTDR',
    plate: 'KLU-3011',
    phone: '(98) 99100-3344',
    region: 'São Cristóvão / Tirirical',
    city: 'São Luís',
    neighborhood: 'Tirirical',
    currentOSId: 'os-103',
    activityTimeMinutes: 75,
    lastSeen: 'Há 2 min',
    lastLocation: { lat: -2.551, lng: -44.215, speed: 0, heading: 0 },
  },
  'tech-5': {
    id: 'tech-5',
    name: 'Equipe Echo (Gabriel)',
    techs: ['Gabriel Santos'],
    status: 'Aguardando cliente',
    battery: 79,
    vehicle: 'Saveiro Tech',
    plate: 'NWX-1020',
    phone: '(98) 98221-5544',
    region: 'Anjo da Guarda',
    city: 'São Luís',
    neighborhood: 'Anjo da Guarda',
    currentOSId: 'os-106',
    activityTimeMinutes: 12,
    lastSeen: 'Há 4 min',
    lastLocation: { lat: -2.568, lng: -44.312, speed: 0, heading: 0 },
  },
  'tech-6': {
    id: 'tech-6',
    name: 'Equipe Foxtrot (Intervalo)',
    techs: ['Vitor Hugo'],
    status: 'Em intervalo',
    battery: 50,
    vehicle: 'YBR 150',
    plate: 'PSJ-7711',
    phone: '(98) 98877-6611',
    region: 'Turu / Araçagi',
    city: 'São Luís',
    neighborhood: 'Turu',
    activityTimeMinutes: 40,
    lastSeen: 'Há 15 min',
    lastLocation: { lat: -2.485, lng: -44.225, speed: 0, heading: 0 },
  },
  'tech-7': {
    id: 'tech-7',
    name: 'Equipe Golf (Offline)',
    techs: ['Marcelo Diniz'],
    status: 'Offline',
    battery: 12,
    vehicle: 'Uno Mille',
    plate: 'HPX-3312',
    phone: '(98) 98122-0099',
    region: 'Maiobão',
    city: 'Paço do Lumiar',
    neighborhood: 'Maiobão',
    lastSeen: 'Há 2h',
    lastLocation: { lat: -2.521, lng: -44.185, speed: 0, heading: 0 },
  },
}

export const MOCK_ORDERS: ServiceOrder[] = [
  {
    ixcId: 'os-101',
    number: '98412',
    client: 'Condomínio Grand Park - Apt 402',
    address: 'Av. Colares Moreira, 1000',
    neighborhood: 'Renascença',
    city: 'São Luís',
    phone: '(98) 98844-1234',
    whatsapp: '5598988441234',
    subject: 'Sem conexão de internet (ONU LOS piscando vermelho)',
    category: 'Sem conexão',
    technology: 'FTTH GPON',
    priority: 'critica',
    status: 'DS',
    lat: -2.502,
    lng: -44.292,
    teamId: 'tech-1',
    teamName: 'Equipe Alpha',
    openedAt: '10 min atrás',
    slaMinutes: 120,
    slaRemainingMinutes: 45,
    ctoName: 'CTO-REN-04',
    ctoPort: '06/16',
    rxSignal: -29.8,
    txSignal: 2.1,
    distance: 1.4,
    eta: '6 min',
    equipment: 'Fiberhome HG6145F',
  },
  {
    ixcId: 'os-102',
    number: '98415',
    client: 'Supermercado Mateus - Cohama',
    address: 'Av. Daniel de La Touche, 450',
    neighborhood: 'Cohama',
    city: 'São Luís',
    phone: '(98) 98111-9988',
    subject: 'Lentidão no Wi-Fi das maquininhas de cartão',
    category: 'Lentidão',
    technology: 'FTTH GPON',
    priority: 'alta',
    status: 'EX',
    lat: -2.529,
    lng: -44.258,
    teamId: 'tech-2',
    teamName: 'Equipe Bravo',
    openedAt: '45 min atrás',
    slaMinutes: 180,
    slaRemainingMinutes: 90,
    ctoName: 'CTO-COH-12',
    ctoPort: '02/16',
    rxSignal: -22.1,
    txSignal: 2.4,
    distance: 0,
    eta: 'No local',
    equipment: 'Huawei HG8145V5',
  },
  {
    ixcId: 'os-103',
    number: '98420',
    client: 'Rompimento de Fibra Alimentadora (Rua da Estrela)',
    address: 'Av. Guajajaras, 220',
    neighborhood: 'Tirirical',
    city: 'São Luís',
    subject: 'Fibra rompida por caminhão com carga alta',
    category: 'Fibra rompida',
    technology: 'Backbone 24FO',
    priority: 'critica',
    status: 'EX',
    lat: -2.552,
    lng: -44.218,
    teamId: 'tech-4',
    teamName: 'Equipe Delta (Infra Fusão)',
    openedAt: '1h 15min atrás',
    slaMinutes: 240,
    slaRemainingMinutes: 30,
    ctoName: 'CEO-TIR-01',
    ctoPort: 'N/A',
    rxSignal: -99,
    txSignal: 0,
    distance: 0,
    eta: 'Em manutenção',
    equipment: 'Caixa de Emenda 24FO',
  },
  {
    ixcId: 'os-104',
    number: '98422',
    client: 'Dra. Vanessa Meireles (Clínica Ocular)',
    address: 'Rua do Sol, 310',
    neighborhood: 'Centro',
    city: 'São Luís',
    subject: 'Mudança de endereço Comercial',
    category: 'Mudança de endereço',
    technology: 'FTTH 500M',
    priority: 'media',
    status: 'A',
    lat: -2.531,
    lng: -44.302,
    openedAt: '2h atrás',
    slaMinutes: 360,
    slaRemainingMinutes: 210,
    ctoName: 'CTO-CEN-08',
    ctoPort: 'Disponível',
    equipment: 'ZTE F670L',
  },
  {
    ixcId: 'os-105',
    number: '98425',
    client: 'Carlos Alberto Fonseca',
    address: 'Rua das Hortênsias, Qda 12',
    neighborhood: 'Calhau',
    city: 'São Luís',
    subject: 'Instalação nova de Fibra Óptica 1Gbps',
    category: 'Instalação',
    technology: 'FTTH Wi-Fi 6',
    priority: 'media',
    status: 'A',
    lat: -2.491,
    lng: -44.279,
    openedAt: '30 min atrás',
    slaMinutes: 480,
    slaRemainingMinutes: 410,
    ctoName: 'CTO-CAL-15',
    ctoPort: '04/16',
    rxSignal: -19.5,
    equipment: 'Huawei Wi-Fi 6 AX3',
  },
  {
    ixcId: 'os-106',
    number: '98428',
    client: 'Residência Maria das Graças',
    address: 'Rua da Paz, 45',
    neighborhood: 'Anjo da Guarda',
    city: 'São Luís',
    subject: 'Configuração de senha do Roteador / Mesh',
    category: 'Configuração de roteador',
    technology: 'FTTH 300M',
    priority: 'baixa',
    status: 'A',
    lat: -2.569,
    lng: -44.310,
    teamId: 'tech-5',
    teamName: 'Equipe Echo',
    openedAt: '3h atrás',
    slaMinutes: 360,
    slaRemainingMinutes: 120,
    ctoName: 'CTO-ANG-03',
    ctoPort: '08/16',
    rxSignal: -23.4,
    equipment: 'Intelbras Twibi',
  },
  {
    ixcId: 'os-107',
    number: '98430',
    client: 'Escritório de Advocacia Castro & Siqueira',
    address: 'Av. dos Holandeses, 1200',
    neighborhood: 'Calhau',
    city: 'São Luís',
    subject: 'Sem conexão em múltiplos computadores',
    category: 'Sem conexão',
    technology: 'FTTH GPON',
    priority: 'critica',
    status: 'A',
    lat: -2.488,
    lng: -44.269,
    openedAt: '5 min atrás',
    slaMinutes: 120,
    slaRemainingMinutes: 115,
    ctoName: 'CTO-HOL-09',
    ctoPort: '01/16',
    rxSignal: -31.2,
    equipment: 'Nokia G-140W-H',
  },
  {
    ixcId: 'os-108',
    number: '98433',
    client: 'Padaria Pão Quente',
    address: 'Av. São Luís Rei de França, 88',
    neighborhood: 'Turu',
    city: 'São Luís',
    subject: 'Retirada de equipamento por cancelamento',
    category: 'Retirada de equipamentos',
    technology: 'FTTH',
    priority: 'baixa',
    status: 'A',
    lat: -2.489,
    lng: -44.232,
    openedAt: '4h atrás',
    slaMinutes: 600,
    slaRemainingMinutes: 320,
    ctoName: 'CTO-TUR-22',
    equipment: 'ONU Fiberhome',
  },
]

export const MOCK_CLUSTERS: IncidentCluster[] = [
  {
    id: 'cluster-1',
    title: 'POSSÍVEL FUSÃO / QUEDA CTO-TIR-01 (Tirirical)',
    category: 'Fibra rompida',
    city: 'São Luís',
    neighborhood: 'Tirirical',
    ctoName: 'CEO-TIR-01',
    affectedCount: 8,
    lat: -2.551,
    lng: -44.217,
    osIds: ['os-103'],
    severity: 'critica',
  },
  {
    id: 'cluster-2',
    title: 'ALERTA DE SINAL FRACO / ATENUAÇÃO (Calhau)',
    category: 'Sem conexão',
    city: 'São Luís',
    neighborhood: 'Calhau',
    ctoName: 'CTO-HOL-09',
    affectedCount: 4,
    lat: -2.489,
    lng: -44.271,
    osIds: ['os-107'],
    severity: 'alta',
  },
]

export const MOCK_STATS: DashboardStats = {
  active: 7,
  total: 15,
  osToday: 32,
  osDone: 18,
  osProgress: 4,
  osPending: 10,
  avgTime: 38,
  completionRate: 78,
  osOpen: 8,
  osOverdue: 2,
  clientsWaiting: 6,
  onlineTechs: 6,
  attendingTechs: 2,
  drivingTechs: 1,
  stoppedTechs: 1,
  offlineTechs: 1,
  avgDriveTime: 14,
  avgServiceTime: 28,
  slaComplianceRate: 94,
}

export const MOCK_ALERTS: Alert[] = [
  {
    id: 'alert-1',
    type: 'danger',
    title: '💥 Alerta de Rompimento Massivo',
    message: 'Detectadas 8 O.S. de "Sem Conexão" ancoradas na CEO-TIR-01 (Tirirical). Equipe Delta atribuída.',
    neighborhood: 'Tirirical',
    timestamp: new Date(),
  },
  {
    id: 'alert-2',
    type: 'warning',
    title: '⚠️ SLA Restante Crítico (< 30 min)',
    message: 'O.S. 98412 (Renascença) com SLA vencendo em 45 minutos. Equipe Alpha a 6 min de distância.',
    osId: 'os-101',
    timestamp: new Date(Date.now() - 5 * 60 * 1000),
  },
  {
    id: 'alert-3',
    type: 'info',
    title: '💡 Sugestão de Auto-Dispatch',
    message: 'Equipe Charlie está DISPONÍVEL a 1.2km da O.S. 98425 (Calhau). Clique para atribuir.',
    technician: 'Equipe Charlie',
    osId: 'os-105',
    timestamp: new Date(Date.now() - 12 * 60 * 1000),
  },
]
